apiVersion: v2
name: gatekeeper-library
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/website/static/img/logo.svg
type: application
version: 0.2.5
appVersion: 52cb14a2ef7a9d06908e1543524f283290b8b4f4
sources:
  - https://github.com/jouve/charts
  - https://github.com/open-policy-agent/gatekeeper-library
maintainers:
  - name: jouve
    url: https://github.com/jouve
annotations:
  artifacthub.io/license: Apache-2.0
