{{- if .Values.deployment.enabled }}
{{- if not .Values.deployment.skipConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "coredns.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "coredns.labels" . | nindent 4 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.customAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  Corefile: |-
    {{- range $name, $conf := .Values.extraConfig }}
    {{ $name }}{{ if $conf.parameters }} {{ $conf.parameters }}{{ end }}
    {{- end }}
    {{ range .Values.servers }}
    {{- range $idx, $zone := .zones }}{{ if $idx }} {{ end }}{{ default "" $zone.scheme }}{{ default "." $zone.zone }}{{ else }}.{{ end -}}{{ if .port }}:{{ .port }}{{ end }} {
      {{- range .plugins }}
        {{ .name }}{{ with .parameters }} {{ include "common.tplvalues.render" (dict "value" . "context" $) }}{{ end }}{{ with .configBlock }} {
          {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 10 }}
        }
        {{- end }}
      {{- end }}
    }
    {{ end }}
  {{- range .Values.zoneFiles }}
  {{ .filename }}: {{- include "common.tplvalues.render" (dict "value" .contents "context" $) | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
