apiVersion: v2
name: subnamespace
description: SubnamespaceAnchor is the Schema for the subnamespace API
type: application
version: 0.2.10
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
sources:
- https://github.com/jouve/charts
- https://github.com/kubernetes-sigs/hierarchical-namespaces
maintainers:
- name: jouve
  url: https://github.com/jouve
annotations:
  artifacthub.io/license: GPL-3.0-or-later
