apiVersion: v2
name: hnc
description: Hierarchical Namespace Controller (HNC). Policies and delegated creation to Kubernetes namespaces.
icon: https://raw.githubusercontent.com/KDE/breeze-icons/master/icons/actions/16/view-list-tree.svg
type: application
version: 0.6.9
appVersion: v1.1.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
sources:
- https://github.com/jouve/charts
- https://github.com/kubernetes-sigs/hierarchical-namespaces
maintainers:
- name: jouve
  url: https://github.com/jouve
annotations:
  artifacthub.io/license: GPL-3.0-or-later
