apiVersion: v2
name: coredns
version: 1.30.1
appVersion: 1.11.1
home: https://coredns.io
icon: https://coredns.io/images/CoreDNS_Colour_Horizontal.png
description: CoreDNS is a DNS server that chains plugins and provides Kubernetes DNS Services
keywords:
  - coredns
  - dns
  - kubedns
sources:
  - https://github.com/coredns/coredns
maintainers:
  - name: mrueg
  - name: haad
  - name: hagaibarel
  - name: shubham-cmyk
type: application
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Allow overriding the selectors for Deployment, Services, PodDisruptionBudget and ServiceMonitor
    - kind: added
      description: Setting `clusterRole.nameOverride` to allow overriding the ClusterRole name.
