apiVersion: v2
name: postgresql
description: Deploy postgresql using cloudnative-pg operator
icon: https://raw.githubusercontent.com/cloudnative-pg/artwork/main/cloudnativepg-logo.svg
type: application
keywords:
- database
- postgresql
- cloudnative-pg
version: 0.8.9
appVersion: "17.4"
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
sources:
- https://github.com/jouve/charts
- https://cloudnative-pg.io/
maintainers:
- name: jouve
  url: https://github.com/jouve
annotations:
  artifacthub.io/images: |
    - name: postgresql
      image: ghcr.io/cloudnative-pg/postgresql:16.3-1
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg
